### ISSUE TITLE
평균계산은 반복문내에서 수행하지 않아야 합니다

### ISSUE THREAD

**Issue by callor** [WHM0304/Biz-2023-11-505-Java#2]
![image](https://github.com/WHM0304/Biz-2023-11-505-Java/assets/23270330/ded88784-817e-4010-b667-d48eb4173bff)

평균의 계산은 반복문내에서 수행하지 않는 것이 좋습니다.
반복문내에서 계산된 평균은 오차를 일으킬수 있습니다

**Comment by WHM0304** [comment]
변경했습니다.
